# Generated by Django 3.0.8 on 2020-07-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField()),
                ('task_name', models.CharField(max_length=200)),
                ('task_hour', models.IntegerField(verbose_name=2)),
            ],
        ),
    ]
